// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aucjzlhoegpnktlbkipt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1Y2p6bGhvZWdwbmt0bGJraXB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3NTIwMTEsImV4cCI6MjA1NTMyODAxMX0.PG4JRrA56u1vOzNFfiGZ5yaKZjmStfh0fvNRhKU6mSg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);